config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'pages/directions'
  get 'pages/about'
  get 'pages/news'
  get 'pages/articles'
  get 'pages/contacts'

  get 'get_subgroups/:group_id', to: 'api#get_subgroups'  
  get 'get_products/:subgroup_id', to: 'api#get_products'

  get 'new_group', to: 'products#new_group'
  post 'new_group', to: 'products#create_group'
  
  get 'new_subgroup/:group_id', to: 'products#new_subgroup'
  post 'new_subgroup/:group_id', to: 'products#create_subgroup'
  
  get 'new_thermal_range', to: 'products#new_thermal_range'
  post 'new_thermal_range', to: 'products#create_thermal_range'

  get '/product_search' => 'api#product_search'

  resources :products

  root 'pages#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/price.rb
# == Schema Information
#
# Table name: prices
#
#  id         :integer          not null, primary key
#  option     :string
#  price      :decimal(, )
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  product_id :integer          not null
#
# Indexes
#
#  index_prices_on_product_id  (product_id)
#
# Foreign Keys
#
#  product_id  (product_id => products.id)
#
class Price < ApplicationRecord
  belongs_to :product
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id                  :integer          not null, primary key
#  code                :integer
#  name                :integer
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  productsubgroup_id  :integer          not null
#  temperaturerange_id :integer          not null
#
# Indexes
#
#  index_products_on_code                 (code) UNIQUE
#  index_products_on_productsubgroup_id   (productsubgroup_id)
#  index_products_on_temperaturerange_id  (temperaturerange_id)
#
# Foreign Keys
#
#  productsubgroup_id   (productsubgroup_id => productsubgroups.id)
#  temperaturerange_id  (temperaturerange_id => temperatureranges.id)
#
class Product < ApplicationRecord
  belongs_to :productsubgroup
  has_many :prices
  has_one :temperature_range
end

app/models/product_group.rb
# == Schema Information
#
# Table name: product_groups
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class ProductGroup < ApplicationRecord
	has_many :product_subgroups
end

app/models/product_subgroup.rb
# == Schema Information
#
# Table name: product_subgroups
#
#  id               :integer          not null, primary key
#  name             :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  product_group_id :integer          not null
#
# Indexes
#
#  index_product_subgroups_on_product_group_id  (product_group_id)
#
# Foreign Keys
#
#  product_group_id  (product_group_id => product_groups.id)
#
class ProductSubgroup < ApplicationRecord
  belongs_to :product_group
  has_many :products
end

app/models/temperature_range.rb
# == Schema Information
#
# Table name: temperature_ranges
#
#  id         :integer          not null, primary key
#  range      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class TemperatureRange < ApplicationRecord
  belongs_to :product
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
	def get_subgroups
		group = ProductGroup.find(params[:group_id])
		@subgroups = group.product_subgroups
    respond_to do |format|
      format.json { render json: @subgroups }
    end
	end

  def product_search
    if params[:subgroup].present? && params[:subgroup].strip != ""
      @courses = Course.where("location_id = ?", params[:location])
    else
      @courses = Course.all
    end
  end

	def get_products
		subgroup = ProductSubgroup.find(params[:subgroup_id])
		@products = subgroup.products
    respond_to do |format|
      format.json { render json: @products }
    end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def directions
  end

  def about
  end

  def news
  end

  def articles
  end

  def contacts
  end
end

app/controllers/product_groups_controller.rb
class ProductGroupsController < ApplicationController
	def index
	end

	def new
		@product = Product.new
		@product_groups = ProductGroup.all
		@product_subgroups = ProductSubgroup.all
	end

	def create
		@product = Product.new
	end
end

app/controllers/product_subgroups_controller.rb
class ProductSubgroupsController < ApplicationController
	def index
	end

	def new_subgroup
	end

	def new_group
	end

	def new_thr
	end

	def create_subgroup
	end

	def create_group
	end

	def create_thr
	end

	def new
		@product = Product.new
		@product_groups = ProductGroup.all
		@product_subgroups = ProductSubgroup.all
	end

	def create
		@product = Product.new
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
	end

	def new_subgroup
	end

	def new_group
	end

	def new_thermal_range
	end

	def create_subgroup
	end

	def create_group
	end

	def create_thermal_range
	end

	def new
		@product = Product.new
		@product_groups = ProductGroup.all
		@product_subgroups = ProductSubgroup.all
		@temperature_range = TemperatureRange.all
	end

	def create
		render plain: params[:group]
		@product = Product.new
	end

  private
    def product_params
      params.require(:product).permit(:name, :code)
      params.require(:subgroup).permit(:id)
    end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dieta</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>
<%ApplicationController.descendants.each do |p|%>
<%p.action_methods.each do |m|%>
<p>
<%=m%>
</p>
<%end%>
<%end%>

app/views/products/create.html.erb
create

app/views/products/index.html.erb
<script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.js"></script>

<h1>Isotope - filtering</h1>

<div class="button-group filters-button-group">
  <button class="button is-checked" data-filter="*">show all</button>
  <button class="button" data-filter=".metal">metal</button>
  <button class="button" data-filter=".transition">transition</button>
  <button class="button" data-filter=".alkali, .alkaline-earth">alkali and alkaline-earth</button>
  <button class="button" data-filter=":not(.transition)">not transition</button>
  <button class="button" data-filter=".metal:not(.transition)">metal but not transition</button>
  <button class="button" data-filter="numberGreaterThan50">number > 50</button>
  <button class="button" data-filter="ium">name ends with &ndash;ium</button>
</div>

<div class="grid">
  <div class="element-item transition metal " data-category="transition">
    <h3 class="name">Mercury</h3>
    <p class="symbol">Hg</p>
    <p class="number">80</p>
    <p class="weight">200.59</p>
  </div>
  <div class="element-item metalloid " data-category="metalloid">
    <h3 class="name">Tellurium</h3>
    <p class="symbol">Te</p>
    <p class="number">52</p>
    <p class="weight">127.6</p>
  </div>
  <div class="element-item post-transition metal " data-category="post-transition">
    <h3 class="name">Bismuth</h3>
    <p class="symbol">Bi</p>
    <p class="number">83</p>
    <p class="weight">208.980</p>
  </div>
  <div class="element-item post-transition metal " data-category="post-transition">
    <h3 class="name">Lead</h3>
    <p class="symbol">Pb</p>
    <p class="number">82</p>
    <p class="weight">207.2</p>
  </div>
  <div class="element-item transition metal " data-category="transition">
    <h3 class="name">Gold</h3>
    <p class="symbol">Au</p>
    <p class="number">79</p>
    <p class="weight">196.967</p>
  </div>
  <div class="element-item alkali metal " data-category="alkali">
    <h3 class="name">Potassium</h3>
    <p class="symbol">K</p>
    <p class="number">19</p>
    <p class="weight">39.0983</p>
  </div>
  <div class="element-item alkali metal " data-category="alkali">
    <h3 class="name">Sodium</h3>
    <p class="symbol">Na</p>
    <p class="number">11</p>
    <p class="weight">22.99</p>
  </div>
  <div class="element-item transition metal " data-category="transition">
    <h3 class="name">Cadmium</h3>
    <p class="symbol">Cd</p>
    <p class="number">48</p>
    <p class="weight">112.411</p>
  </div>
  <div class="element-item alkaline-earth metal " data-category="alkaline-earth">
    <h3 class="name">Calcium</h3>
    <p class="symbol">Ca</p>
    <p class="number">20</p>
    <p class="weight">40.078</p>
  </div>
  <div class="element-item transition metal " data-category="transition">
    <h3 class="name">Rhenium</h3>
    <p class="symbol">Re</p>
    <p class="number">75</p>
    <p class="weight">186.207</p>
  </div>
  <div class="element-item post-transition metal " data-category="post-transition">
    <h3 class="name">Thallium</h3>
    <p class="symbol">Tl</p>
    <p class="number">81</p>
    <p class="weight">204.383</p>
  </div>
  <div class="element-item metalloid " data-category="metalloid">
    <h3 class="name">Antimony</h3>
    <p class="symbol">Sb</p>
    <p class="number">51</p>
    <p class="weight">121.76</p>
  </div>
  <div class="element-item transition metal " data-category="transition">
    <h3 class="name">Cobalt</h3>
    <p class="symbol">Co</p>
    <p class="number">27</p>
    <p class="weight">58.933</p>
  </div>
  <div class="element-item lanthanoid metal inner-transition " data-category="lanthanoid">
    <h3 class="name">Ytterbium</h3>
    <p class="symbol">Yb</p>
    <p class="number">70</p>
    <p class="weight">173.054</p>
  </div>
  <div class="element-item noble-gas nonmetal " data-category="noble-gas">
    <h3 class="name">Argon</h3>
    <p class="symbol">Ar</p>
    <p class="number">18</p>
    <p class="weight">39.948</p>
  </div>
  <div class="element-item diatomic nonmetal " data-category="diatomic">
    <h3 class="name">Nitrogen</h3>
    <p class="symbol">N</p>
    <p class="number">7</p>
    <p class="weight">14.007</p>
  </div>
  <div class="element-item actinoid metal inner-transition " data-category="actinoid">
    <h3 class="name">Uranium</h3>
    <p class="symbol">U</p>
    <p class="number">92</p>
    <p class="weight">238.029</p>
  </div>
  <div class="element-item actinoid metal inner-transition " data-category="actinoid">
    <h3 class="name">Plutonium</h3>
    <p class="symbol">Pu</p>
    <p class="number">94</p>
    <p class="weight">(244)</p>
  </div>
</div>

app/views/products/new.html.erb
<container>
  <h1> Create new product </h1>



  <%= form_with model: @product do |form| %>
    <div id="group">
      <%= select_tag "group", 
          options_from_collection_for_select(ProductGroup.all, "id", "name"), 
          prompt: "Group", 
          class: "custom-select mb-0 mr-sm-0 mb-sm-0" %>
      <%= link_to 'New group', 
           new_group_path, 
          class: 'btn btn-primary btn-sm' %>
    </div>

    <div id="subgroup" style="display: none;">
      <%= select_tag "subgroup", prompt: "Subgroup", class: "custom-select mb-0 mr-sm-0 mb-sm-0 hidden" %>
      <%= link_to 'New subgroup', "/", class: 'btn btn-primary', id: 'create_subgroup' %>
    </div>

    <div id="temperature">
      <%= select_tag "group", 
          options_from_collection_for_select(TemperatureRange.all, "id", "name"), 
          prompt: "Thermal Range", 
          class: "custom-select mb-0 mr-sm-0 mb-sm-0" %>
      <%= link_to 'New thermal range', 
          new_thermal_range_path, 
          class: 'btn btn-primary btn-sm' %>
    </div>

    <div id="product" style="display: none;">
      <%= form.label :name %><br>
      <%= form.text_field :name %>

      <%= form.label :code %><br>
      <%= form.text_field :code %>
    </div>

    <div id="create" style="display: none;">
      <%= form.submit %>
    </div>
  <% end %>
</container>

app/views/shared/_header.html.erb
<section>
  <div class="content mb-3">
   <%= link_to 'Directions', pages_directions_path, class: 'btn btn-primary' %>
   <%= link_to 'About', pages_about_path, class: 'btn btn-primary' %>
   <%= link_to 'News', pages_news_path, class: 'btn btn-primary' %>
   <%= link_to 'Articles', pages_articles_path, class: 'btn btn-primary' %>
   <%= link_to 'Contacts', pages_contacts_path, class: 'btn btn-primary' %>
   <%= link_to 'Products', products_path, class: 'btn btn-primary' %>
  </div>
</section>